// <auto-generated />
using System;
using CsvWorker.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsvWorker.CLI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117183957_AddedIndexesForSearchOptimiztion")]
    partial class AddedIndexesForSearchOptimiztion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CsvWorker.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DoLocationId")
                        .HasColumnType("int")
                        .HasColumnName("DOLocationID");

                    b.Property<DateTime>("DropoffDateTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("tpep_dropoff_datetime");

                    b.Property<decimal?>("FareAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fare_amount");

                    b.Property<short?>("PassengerCount")
                        .HasColumnType("smallint")
                        .HasColumnName("passenger_count");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("tpep_pickup_datetime");

                    b.Property<int?>("PuLocationId")
                        .HasColumnType("int")
                        .HasColumnName("PULocationID");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("store_and_fwd_flag");

                    b.Property<decimal?>("TipAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tip_amount");

                    b.Property<decimal?>("TripDistance")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("trip_distance");

                    b.Property<int>("TripDurationSeconds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("trip_duration_seconds")
                        .HasComputedColumnSql("DATEDIFF(SECOND, tpep_pickup_datetime, tpep_dropoff_datetime)", true);

                    b.HasKey("Id");

                    b.HasIndex("PuLocationId")
                        .HasDatabaseName("IX_trips_PULocationID");

                    b.HasIndex("TripDistance")
                        .HasDatabaseName("IX_trips_TripDistance");

                    b.HasIndex("TripDurationSeconds")
                        .HasDatabaseName("IX_trips_TripDurationSeconds");

                    b.ToTable("trips", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
